In [ ]:
#TO Create final trainable CSV with respective band ratios
#For Chlorophyll only

import pandas as pd

chlorophyll_withoutBR= pd.read_csv("D:\Shukra_sir\MLAllTraining\ForTraining\Chlorophyll.csv") 
chlorophyll_withBR1 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Chlorophyll\\NewChlorophyll_BandRatio1.csv")
chlorophyll_withBR2 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Chlorophyll\\NewChlorophyll_BandRatio2.csv")
chlorophyll_withBR3 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For Chlorophyll\\NewChlorophyll_BandRatio3.csv")

doc_withoutBR = pd.read_csv("D:\Shukra_sir\MLAllTraining\ForTraining\DOC.csv")
doc_withBR1 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio1.csv")
doc_withBR2 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio2.csv")
doc_withBR3 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio3.csv")

In [ ]:
#Band Ratio with Highest Correlations, looked manually

"""
A. FOR CHLOROPHYLL
a. for BandRatio1: 
Top three are: 
i. "B2_minus_B5", 
ii. "B3_minus_B2", 
iii. "B2_minus_B4",

    
b. for Band Ratio2:
Top three are: 
i. "B3_div_B5", 
ii. "B2_div_B5", 
iii. "B2_div_B4"

    
c. for Band Ratio3:
Top three are: 
i. "ND_B5_B3",
ii. "ND_B2_B5",
iii."ND_B4_B2"

"""


"""
A. FOR DOC
a. for BandRatio1: 
Top three are: 
i. 
ii. 
iii.
b. for Band Ratio2:
Top three are: 
i. 
ii. 
iii.

c. for Band Ratio3:
Top three are: 
i. 
ii. 
iii.
"""

'\nA. FOR DOC\na. for BandRatio1: \nTop three are: \ni. \nii. \niii.\nb. for Band Ratio2:\nTop three are: \ni. \nii. \niii.\n\nc. for Band Ratio3:\nTop three are: \ni. \nii. \niii.\n'

In [23]:
"For Chlorophyll only"

top_BR1 = [
    "B2_minus_B5",
    "B3_minus_B2",
    "B2_minus_B4"
]

top_BR2 = [
    "B3_div_B5",
    "B2_div_B5",
    "B2_div_B4"
]

top_BR3 = [
    "ND_B5_B3",
    "ND_B2_B5",
    "ND_B4_B2"
]

In [24]:
df_base = chlorophyll_withoutBR
df_BR1 = chlorophyll_withBR1
df_BR2 = chlorophyll_withBR2
df_BR3 = chlorophyll_withBR3

df_BR1_sel = df_BR1[top_BR1]
df_BR2_sel = df_BR2[top_BR2]
df_BR3_sel = df_BR3[top_BR3]

In [25]:
df_BR1_sel

     B2_minus_B5  B3_minus_B2  B2_minus_B4
0        -0.0514       0.0178      -0.0266
1        -0.0180       0.0088      -0.0044
2        -0.0237       0.0091      -0.0025
3        -0.0774       0.0400      -0.0584
4        -0.0624       0.0288      -0.0513
..           ...          ...          ...
541      -0.0592       0.0275      -0.0309
542      -0.0683       0.0263      -0.0376
543      -0.0493       0.0276      -0.0179
544      -0.0872       0.0344      -0.0495
545      -0.0701       0.0268      -0.0443

[546 rows x 3 columns]

In [26]:
df_final = pd.concat(
    [df_base, df_BR1_sel, df_BR2_sel, df_BR3_sel],
    axis=1
)

df_final

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,method_name,B2_minus_B5,B3_minus_B2,B2_minus_B4,B3_div_B5,B2_div_B5,B2_div_B4,ND_B5_B3,ND_B2_B5,ND_B4_B2
0,2019-09-17 18:00:00,0.0624,0.1123,0.0881,0.0374,0.0552,0.0640,0.0888,0.0950,0.1004,...,Std Method 10200 H,-0.0514,0.0178,-0.0266,0.621615,0.421166,0.584366,0.233332,-0.407287,0.262325
1,2020-09-16 19:00:00,0.0681,0.0494,0.0391,0.0484,0.0572,0.0528,0.0664,0.0598,0.0631,...,Std Method 10200 H,-0.0180,0.0088,-0.0044,0.861433,0.728905,0.916649,0.074433,-0.156793,0.043478
2,2021-04-21 19:45:00,0.0791,0.0847,0.0622,0.0517,0.0608,0.0542,0.0754,0.0771,0.0713,...,Std Method 10200 H,-0.0237,0.0091,-0.0025,0.806355,0.685667,0.953857,0.107195,-0.186466,0.023607
3,2021-06-25 18:45:00,0.1207,0.2477,0.2172,0.1576,0.1976,0.2160,0.2350,0.2393,0.2288,...,Std Method 10200 H,-0.0774,0.0400,-0.0584,0.840847,0.670635,0.729626,0.086454,-0.197147,0.156316
4,2022-02-25 22:00:00,0.0915,0.1924,0.1699,0.1251,0.1539,0.1764,0.1875,0.1910,0.1903,...,Std Method 10200 H,-0.0624,0.0288,-0.0513,0.820796,0.667196,0.709180,0.098418,-0.199615,0.170149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,2023-08-22 17:13:00,0.0535,0.1462,0.1204,0.0581,0.0856,0.0890,0.1173,0.1680,0.1990,...,Std Method 10200 H,-0.0592,0.0275,-0.0309,0.729747,0.495307,0.652802,0.156234,-0.337512,0.210060
542,2023-09-06 16:22:00,0.0469,0.1503,0.1177,0.0501,0.0764,0.0877,0.1184,0.1803,0.2028,...,Std Method 10200 H,-0.0683,0.0263,-0.0376,0.645265,0.423138,0.571259,0.215605,-0.405339,0.272857
543,2019-10-07 17:15:00,0.0380,0.1134,0.0714,0.0352,0.0628,0.0531,0.0845,0.0913,0.1007,...,Std Method 10200 H,-0.0493,0.0276,-0.0179,0.743186,0.416563,0.662888,0.147317,-0.411860,0.202716
544,2021-08-02 15:13:00,0.0722,0.2492,0.2019,0.0845,0.1189,0.1340,0.1717,0.1995,0.2076,...,Std Method 10200 H,-0.0872,0.0344,-0.0495,0.692483,0.492135,0.630592,0.181692,-0.340358,0.226544
545,2021-10-11 16:46:00,0.0474,0.1927,0.1681,0.0685,0.0953,0.1128,0.1386,0.1510,0.1564,...,Std Method 10200 H,-0.0701,0.0268,-0.0443,0.687585,0.494224,0.607264,0.185121,-0.338482,0.244345

In [27]:
output_file = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\TrainableWithBandRatios\\Chlorophyll_BR.csv" 
df_final.to_csv(output_file, index=False)

In [28]:
#FOR DOC

doc_withoutBR = pd.read_csv("D:\Shukra_sir\MLAllTraining\ForTraining\DOC.csv")
doc_withBR1 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio1.csv")
doc_withBR2 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio2.csv")
doc_withBR3 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For DOC\\NewDOC_BandRatio3.csv")

In [30]:
"For DOC only"

top_BR1 = [
    "B4_minus_B3",
    "B2_minus_B4",
    "B5_minus_B2"
]

top_BR2 = [
    "B4_div_B3",
    "B6_div_B8",
    "B3_div_B2"
]

top_BR3 = [
    "ND_B4_B3",
    "ND_B2_B3",
    "ND_B6_B8"
]

In [31]:
df_base = doc_withoutBR
df_BR1 = doc_withBR1
df_BR2 = doc_withBR2
df_BR3 = doc_withBR3

df_BR1_sel = df_BR1[top_BR1]
df_BR2_sel = df_BR2[top_BR2]
df_BR3_sel = df_BR3[top_BR3]

In [32]:
df_final = pd.concat(
    [df_base, df_BR1_sel, df_BR2_sel, df_BR3_sel],
    axis=1
)

df_final

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,method_name,B4_minus_B3,B2_minus_B4,B5_minus_B2,B4_div_B3,B6_div_B8,B3_div_B2,ND_B4_B3,ND_B2_B3,ND_B6_B8
0,2018-06-18 15:30:00,0.0724,0.0885,0.0832,0.0864,0.0921,0.1018,0.1066,0.0937,0.0886,...,EPA 415.1 (D) Ox,0.0097,-0.0154,0.0202,1.105308,0.886463,1.065960,0.050026,-0.031933,-0.060180
1,2020-06-22 14:50:00,0.0864,0.0661,0.0592,0.0738,0.0763,0.0663,0.0643,0.0604,0.0642,...,EPA 415.3 (D),-0.0100,0.0075,-0.0095,0.868927,1.041361,1.033861,-0.070126,-0.016655,0.020270
2,2021-09-20 13:50:00,0.0467,0.0518,0.0457,0.0274,0.0302,0.0305,0.0450,0.0528,0.0547,...,EPA 415.3 (D),0.0003,-0.0031,0.0176,1.009900,2.022911,1.102150,0.004942,-0.048610,0.338399
3,2022-11-14 16:55:00,0.0201,0.0504,0.0506,0.0163,0.0277,0.0300,0.0458,0.0517,0.0502,...,Std Method 5310C (D),0.0023,-0.0137,0.0295,1.082993,2.019452,1.699282,0.039861,-0.259085,0.337641
4,2022-12-19 17:00:00,0.0300,0.0396,0.0330,0.0370,0.0412,0.0350,0.0681,0.0476,0.0650,...,Std Method 5310C (D),-0.0062,0.0020,0.0311,0.849494,1.416625,1.113483,-0.081364,-0.053708,0.172412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,2023-02-08 15:30:00,0.0582,0.1309,0.1072,0.0555,0.0682,0.0861,0.0988,0.1002,0.1072,...,Std Method 5310C (D),0.0179,-0.0306,0.0433,1.262445,0.895434,1.228807,0.116007,-0.102667,-0.055162
850,2022-05-04 14:15:00,0.0704,0.1906,0.1494,0.0709,0.0901,0.1044,0.1356,0.1632,0.1792,...,EPA 415.3 (D),0.0143,-0.0335,0.0647,1.158700,0.864402,1.270786,0.073521,-0.119254,-0.072727
851,2023-02-08 16:00:00,0.0701,0.1366,0.1065,0.0627,0.0730,0.0864,0.0996,0.1184,0.1211,...,Std Method 5310C (D),0.0134,-0.0237,0.0369,1.183545,0.988306,1.164256,0.084065,-0.075902,-0.005877
852,2022-10-12 16:15:00,0.0277,0.1117,0.0540,0.0293,0.0368,0.0240,0.0628,0.1698,0.2056,...,Std Method 5310C (D),-0.0128,0.0053,0.0335,0.652156,0.763143,1.255930,-0.210523,-0.113463,-0.134336
853,2022-10-12 14:30:00,0.0285,0.1106,0.0512,0.0353,0.0438,0.0277,0.0783,0.2093,0.2447,...,Std Method 5310C (D),-0.0161,0.0076,0.0430,0.632406,0.739573,1.240758,-0.225172,-0.107458,-0.149705

In [33]:
output_file = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\TrainableWithBandRatios\\DOC_BR.csv" 
df_final.to_csv(output_file, index=False)

In [2]:
#FOR TSS
import pandas as pd

In [3]:
tss_withoutBR = pd.read_csv("D:\Shukra_sir\MLAllTraining\ForTraining\TSS.csv")
tss_withBR1 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For TSS\\NewTSS_BandRatio1.csv")
tss_withBR2 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For TSS\\NewTSS_BandRatio2.csv")
tss_withBR3 = pd.read_csv("D:\\Shukra_sir\\MLAllTraining\\ForTraining\\Band Ratio and Correlations\\For TSS\\NewTSS_BandRatio3.csv")

In [4]:
"For TSS only"

top_BR1 = [
    "B2_minus_B3",
    "B4_minus_B2",
    "B2_minus_B9"
]

top_BR2 = [
    "B7_div_B8A",
    "B4_div_B3",
    "B8_div_B8A"
]

top_BR3 = [
    "ND_B7_B8A",
    "ND_B4_B3",
    "ND_B2_B4"
]

In [5]:
df_base = tss_withoutBR
df_BR1 = tss_withBR1
df_BR2 = tss_withBR2
df_BR3 = tss_withBR3

df_BR1_sel = df_BR1[top_BR1]
df_BR2_sel = df_BR2[top_BR2]
df_BR3_sel = df_BR3[top_BR3]

In [6]:
df_final = pd.concat(
    [df_base, df_BR1_sel, df_BR2_sel, df_BR3_sel],
    axis=1
)

df_final

,sample_date,B1,B11,B12,B2,B3,B4,B5,B6,B7,...,method_name,B2_minus_B3,B4_minus_B2,B2_minus_B9,B7_div_B8A,B4_div_B3,B8_div_B8A,ND_B7_B8A,ND_B4_B3,ND_B2_B4
0,2021-03-24 17:10:00,0.1372,0.4144,0.3882,0.1933,0.2536,0.3057,0.3315,0.3376,0.3461,...,EPA 160.2,-0.0603,0.1124,-0.1346,0.973556,1.205437,1.011249,-0.013398,0.093152,-0.225250
1,2021-10-20 15:20:00,0.1151,0.3725,0.3337,0.1763,0.2376,0.2869,0.3059,0.3108,0.3180,...,EPA 160.2,-0.0613,0.1106,-0.0934,1.026797,1.207487,1.050045,0.013223,0.093994,-0.238773
2,2024-02-22 19:10:00,0.0986,0.3072,0.2820,0.1756,0.2284,0.2688,0.2812,0.2773,0.2833,...,Std Method 2540 D,-0.0528,0.0932,-0.0752,0.988137,1.176878,1.042550,-0.005965,0.081255,-0.209721
3,2020-02-26 16:00:00,0.0886,0.2972,0.2570,0.1468,0.1729,0.2035,0.2193,0.2299,0.2228,...,EPA 160.2,-0.0261,0.0567,-0.1054,0.942068,1.176974,1.018178,-0.029828,0.081296,-0.161861
4,2020-06-17 16:00:00,0.1388,0.3579,0.3203,0.2189,0.2589,0.3021,0.3130,0.3118,0.3139,...,EPA 160.2,-0.0400,0.0832,-0.1047,0.970622,1.166855,0.984536,-0.014907,0.077005,-0.159693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,2022-05-04 13:50:00,0.0592,0.1982,0.1515,0.0544,0.0737,0.0808,0.1033,0.1488,0.1545,...,EPA 160.2,-0.0193,0.0264,-0.1397,0.996768,1.096322,1.076767,-0.001616,0.045954,-0.195265
683,2023-02-08 15:30:00,0.0582,0.1309,0.1072,0.0555,0.0682,0.0861,0.0988,0.1002,0.1072,...,Std Method 2540 D,-0.0127,0.0306,-0.0569,0.963154,1.262445,1.005382,-0.018764,0.116007,-0.216100
684,2022-05-04 14:15:00,0.0704,0.1906,0.1494,0.0709,0.0901,0.1044,0.1356,0.1632,0.1792,...,EPA 160.2,-0.0192,0.0335,-0.1291,0.966033,1.158700,1.017784,-0.017274,0.073521,-0.191100
685,2023-02-08 16:00:00,0.0701,0.1366,0.1065,0.0627,0.0730,0.0864,0.0996,0.1184,0.1211,...,Std Method 2540 D,-0.0103,0.0237,-0.0865,0.915337,1.183545,0.905511,-0.044199,0.084065,-0.158953
686,2022-10-12 16:15:00,0.0277,0.1117,0.0540,0.0293,0.0368,0.0240,0.0628,0.1698,0.2056,...,Std Method 2540 D,-0.0075,-0.0053,-0.2057,0.903732,0.652156,0.978018,-0.050566,-0.210523,0.099435

In [7]:
output_file = "D:\\Shukra_sir\\MLAllTraining\\ForTraining\\TrainableWithBandRatios\\TSS_BR.csv" 
df_final.to_csv(output_file, index=False)